# What are Multidimensional Arrays in Python?

Medium article posted [here](https://medium.com/@rodrigobc10/what-are-multidimensional-arrays-in-python-8ce82b8cfb41)

# 1D and 2D arrays in Python

In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


Define a helper function

In [2]:
def array_attributes(a):
    print('Data type:\t',a.dtype)
    print('Size (length):\t',a.size)
    print('Dimensions:\t',a.ndim)
    print('Shape:\t\t',a.shape)

In [3]:
array_attributes(a)

Data type:	 int64
Size (length):	 6
Dimensions:	 1
Shape:		 (6,)


# Reshaping 1D arrays into 2D arrays

In [4]:
b = a.reshape(6,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
array_attributes(b)

Data type:	 int64
Size (length):	 6
Dimensions:	 2
Shape:		 (6, 1)


In [6]:
print(b[0]) # outputs [1] 
print(b[0,0]) # outputs 1

[1]
1


In [7]:
c = a.reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
array_attributes(c)

Data type:	 int64
Size (length):	 6
Dimensions:	 2
Shape:		 (2, 3)


# N-Dimensional Arrays

In [9]:
# fixed random seed for repeatability
np.random.seed(seed=10)
array_3d = np.random.randint(-10,10, size = (5,3,2))

In [10]:
array_attributes(array_3d)

Data type:	 int64
Size (length):	 30
Dimensions:	 3
Shape:		 (5, 3, 2)


In [11]:
for i in range(5):
    print(f'array_3d[{i},:,:]')
    print('\n')
    print(array_3d[i,:,:])
    print('\n')

array_3d[0,:,:]


[[ -1  -6]
 [  5 -10]
 [  7   6]]


array_3d[1,:,:]


[[  7  -2]
 [ -1 -10]
 [  0  -2]]


array_3d[2,:,:]


[[-6  9]
 [ 6 -6]
 [ 5  1]]


array_3d[3,:,:]


[[ 1 -9]
 [-2 -6]
 [ 4  7]]


array_3d[4,:,:]


[[ 9  3]
 [-5  3]
 [ 9  3]]




## The axis concept

In [12]:
print(np.sum(array_3d,axis=0))

[[ 10  -5]
 [  3 -29]
 [ 25  15]]


In [13]:
print(np.sum(array_3d,axis=1))

[[ 11 -10]
 [  6 -14]
 [  5   4]
 [  3  -8]
 [ 13   9]]


In [14]:
print(np.sum(array_3d,axis=2))

[[ -7  -5  13]
 [  5 -11  -2]
 [  3   0   6]
 [ -8  -8  11]
 [ 12  -2  12]]


In [15]:
print(np.sum(array_3d,axis=(0,2)))

[  5 -26  40]
